services:
  mysql:
    image: mysql:8.0
    container_name: logistics-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: logistics_tracking
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: password_dev    
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
